config/routes.rb
Rails.application.routes.draw do
  resources :shops do
    resources :mattresses, shallow: true
  end

  root 'shops#new'
  #get '/shops/:shop_id/mattresses' => 'mattresses#index', as: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mattress.rb
class Mattress < ApplicationRecord
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :mattresses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mattresses_controller.rb
class MattressesController < ApplicationController
  before_action :set_mattress, only: %i[ show edit update destroy ]

  # GET /mattresses or /mattresses.json
  def index
    @mattresses = Mattress.includes(:shop)

  end

  # GET /mattresses/1 or /mattresses/1.json
  def show
  end

  # GET /mattresses/new
  def new
    @shop = Shop.find(params[:shop_id])
    @mattress = Mattress.new
  end

  # GET /mattresses/1/edit
  def edit
    @mattress = Mattress.find(params[:id]).includes(:shop)
    @shop = @mattress.shop
  end

  # POST /mattresses or /mattresses.json
  def create
    @shop = Shop.find(params[:shop_id])
    @mattress = @shop.mattresses.new(mattress_params)
    @mattress.shop = @shop


    if @mattress.save
      redirect_to shop_mattresses_path(@mattress)
    else
      redirect_to root_path
    end

  end

  # PATCH/PUT /mattresses/1 or /mattresses/1.json
  def update
    respond_to do |format|
      if @mattress.update(mattress_params)
        format.html { redirect_to mattress_url(@mattress), notice: "Mattress was successfully updated." }
        format.json { render :show, status: :ok, location: @mattress }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mattress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mattresses/1 or /mattresses/1.json
  def destroy
    @mattress.destroy

    respond_to do |format|
      format.html { redirect_to mattresses_url, notice: "Mattress was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mattress
      @mattress = Mattress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mattress_params
      params.require(:mattress).permit(:shop_id, :mattress_name)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.includes(:mattresses)
  end

  # GET /shops/1 or /shops/1.json
  def show
    @shop = Shop.find(params[:id]).includes(:mattresses)
    @mattress = @shop.mattresses
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.create(shop_params)


      if @shop.save
        redirect_to new_shop_mattress_path(@shop)
      end

  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:shop, :shop_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mattresses_helper.rb
module MattressesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bedapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mattresses/_form.html.erb
<%= form_with(model: mattress, url: [@shop, @mattress]) do |form| %>
  <% if mattress.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mattress.errors.count, "error") %> prohibited this mattress from being saved:</h2>

      <ul>
        <% mattress.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mattress, style: "display: block" %>
    <%= form.text_field :shop_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mattresses/_mattress.html.erb
  <p>
    <strong>Shop:</strong>
    <%= mattress.shop_id %>
  </p>

</div>

app/views/mattresses/edit.html.erb
<h1>Editing mattress</h1>

<%= render "form", mattress: @mattress %>

<br>

<div>
  <%= link_to "Show this mattress", @mattress %> |
  <%= link_to "Back to mattresses", mattress_path %>
</div>

app/views/mattresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mattresses</h1>


<div id="mattresses">
  <% @mattresses.each do |mattress| %>
    <%= render mattress %>
    <p>
      <%= link_to "Show this mattress", mattress %>
    </p>
  <% end %>
</div>

<%= link_to "New mattress", new_shop_mattress_path %>

app/views/mattresses/new.html.erb
<h1>New mattress</h1>

<%= render "form", mattress: @mattress %>

<br>

<div>
  <%= link_to "Back to mattresses", shop_mattresses_path %>
</div>

app/views/mattresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mattress %>


<div>
  <%= link_to "Edit this mattress", edit_mattress_path(@mattress) %> |
  <%= link_to "Back to mattresses", shop_mattresses_path(@mattress) %>

  <%= button_to "Destroy this mattress", @mattress, method: :delete %>
</div>

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :shop, style: "display: block" %>
    <%= form.text_field :shop %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Shop:</strong>
    <%= shop.shop %>
  </p>

</div>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= render shop %>
    <p>
      <%= link_to "Show this shop", shop %>
    </p>
  <% end %>
</div>

<%= link_to "New shop", new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>


<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>